### ISSUE TITLE
Replace studlyName in HTML page title with human friendly title

### ISSUE THREAD

**Issue by jadjoubran** [jadsalhani/ionic2-generator#5]
`i2g make:page account_info`
instead of showing the page title as `AccountInfo` we should show it as `Account Info`

I can submit a PR if you think it's a good idea

**Comment by jadjoubran** [comment]
bta3rif shu radd?

**Comment by jadsalhani** [comment]
You'd have to handle the `kebab-case` on the file names as well, so it would generate `account-info.ts`, `account-info.html`, `account-info.scss`

It's going to be added eventually, if you'd like to submit a PR go ahead :smile:
